import { body } from 'express-validator';

export const validateSauceData = [
  body('name')
    .exists()
    .withMessage('Name field is required')
    .bail()
    .isString()
    .withMessage('This value must be a string')
    .bail()
    .trim()
    .not()
    .isEmpty()
    .withMessage('This value is required')
    .bail()
    .matches(/^.{1,14}(?:\s.{1,14})?$/)
    .withMessage(
      'Maximum number of lines: 2. Maximum number of characters per line: 14'
    )
    .escape(),
  body('manufacturer')
    .exists()
    .withMessage('Manufacturer field is required')
    .bail()
    .isString()
    .withMessage('This value must be a string')
    .bail()
    .trim()
    .not()
    .isEmpty()
    .withMessage('This value is required')
    .bail()
    .isLength({ max: 100 })
    .withMessage('Maximum number of characters: 100')
    .escape(),
  body('description')
    .exists()
    .withMessage('Description field is required')
    .bail()
    .isString()
    .withMessage('This value must be a string')
    .bail()
    .trim()
    .not()
    .isEmpty()
    .withMessage('This value is required')
    .bail()
    .isLength({ max: 500 })
    .withMessage('Maximum number of characters: 500')
    .escape(),
  body('mainPepper')
    .exists()
    .withMessage('Main pepper field is required')
    .bail()
    .isString()
    .withMessage('This value must be a string')
    .bail()
    .trim()
    .not()
    .isEmpty()
    .withMessage('This value is required')
    .bail()
    .isLength({ max: 50 })
    .withMessage('Maximum number of characters: 50')
    .escape(),
  body('heat')
    .exists()
    .withMessage('Heat field is required')
    .bail()
    .isInt({ min: 1, max: 10 })
    .withMessage('This value must be a number between 1 and 10 included')
    .bail()
    .not()
    .isEmpty()
    .withMessage('This value is required'),
];

export const validateLikeData = body('like')
  .exists()
  .withMessage('Like field is required')
  .bail()
  .isInt({ min: -1, max: 1 })
  .withMessage('This value must be a number between -1 and 1 included');
